en: 
  languageCode: en-us
  contentDir: content/en
  menu:
    main:
      - name: Bio
        url: /
        weight: 10
      - name: Papers
        url: /#papers
        weight: 11
      - name: News
        url: /#news
        weight: 13
      - name: Experience
        url: experience/
        weight: 20
        main:
      - name: Projects
        url: projects/
        weight: 30
      - name: Teaching
        url: teaching/
        weight: 40
  
ru:
  languageCode: "ru-ru"
  contentDir: "content/ru"
  menu:
    main:
      - name: Обо мне
        url: /
        weight: 10
      - name: Публикации
        url: /#papers
        weight: 11
      - name: Новости
        url: /#news
        weight: 13
      - name: Опыт
        url: experience/
        weight: 20
      - name: Проекты
        url: projects/
        weight: 30
      - name: Курсы
        url: teaching/
        weight: 40
